name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: marvinschopf/install-gcc-arm-none-eabi@main
      - name: Test
        run: if ! command -v arm-none-eabi-gcc&>/dev/null;then echo "arm-none-eabi-gcc could not be found";exit 1;fi
